name: Update Documentation
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

permissions: write-all

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - name: Find PR Comment
      uses: peter-evans/find-comment@v2
      id: fc
      with:
        issue-number: ${{ github.event.number }}
        comment-author: 'github-actions[bot]'
        body-includes: Cloudflare Pages
      if: github.event_name == 'pull_request'
    - name: Comment on PR (Deploy In Progress)
      uses: peter-evans/create-or-update-comment@v3
      id: mc
      with:
        issue-number: ${{ github.event.number }}
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: |
          ## :warning: Cloudflare Pages Deploy In Progress for ${{ github.sha }}...


        edit-mode: replace
      if: github.event_name == 'pull_request'
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install -U -r requirements.txt
    - name: Compile documentation to HTML
      run: |
        sphinx-build -W -b html source build
    - name: Deploy to Pages
      uses: cloudflare/pages-action@1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: skykings-documentation
        directory: build
        branch: ${{ env.PAGES_BRANCH }}
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      env:
        PAGES_BRANCH: ${{ github.event_name == 'push' && github.ref_name ||  format('pr-{0}', github.event.number) }}
    - name: Comment on PR (Deploy Complete)
      uses: peter-evans/create-or-update-comment@v3
      with:
        issue-number: ${{ github.event.number }}
        comment-id: ${{ steps.fc.outputs.comment-id == 0 && steps.mc.outputs.comment-id || steps.fc.outputs.comment-id }}
        body: |
          ## :rocket: Cloudflare Pages Deploy Complete!
          
          Preview it at [pr-${{ github.event.number }}.skykings-documentation.pages.dev](https://pr-${{ github.event.number }}.skykings-documentation.pages.dev)
          Commit ${{ github.sha }}.
        edit-mode: replace
      if: github.event_name == 'pull_request'

