name: Update Documentation
on:
  pull_request:
    branches:
    - main
  workflow_dispatch:

permissions: write-all

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install -U -r requirements.txt
    - name: Compile documentation to HTML
      run: |
        sphinx-build -W -b html source build
    - name: Upload documentation
      uses: EndBug/add-and-commit@v9
      with:
        add: 'build/** -f'
        message: 'Build docs from ${{ github.sha }}'
        default_author: github_actions
