name: Update Documentation
on:
  push:
    branches: [ main ]

permissions: write-all

jobs:
  docs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.11 ]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install -U -r requirements.txt
    - name: Compile documentation to HTML
      run: |
        sphinx-build -W -b html source build
    - name: Upload documentation
      run: |
        cd build
        git init
        git config --local user.name 'github-actions[bot]'
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
        git remote add origin "git@github.com:${{ github.repository }}"
        git add *
        git branch -m production
        git commit -m 'Update docs from {{ github.sha }}'
        git push origin production
