name: Update Documentation
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  workflow_dispatch:

permissions: write-all

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install -U -r requirements.txt
    - name: Compile documentation to HTML
      run: |
        sphinx-build -W -b html source build
    - name: Set env vars for publishing
      run: |
        echo ${{ github.event_name }}
        if "${{ github.event_name }}" = "push"; then echo PAGES_BRANCH=$(echo ${GITHUB_REF#refs/heads/}) >> $GITHUB_ENV; else echo PAGES_BRANCH=pr\-${{github.event.number}}) >> $GITHUB_ENV; fi
        echo ${{ env.PAGES_BRANCH }}
    - name: Deploy to Pages
      uses: cloudflare/pages-action@1
      with:
        apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        projectName: skykings-documentation
        directory: build
        branch: ${{ env.PAGES_BRANCH }}
        gitHubToken: ${{ secrets.GITHUB_TOKEN }}


